name: Test Automation Pipeline

on:
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 0 * * *' # daily at midnight UTC
  workflow_dispatch:
    inputs:
      browser:
        description: 'Select browser for UI tests'
        required: true
        default: 'chrome'
        type: choice
        options:
          - chrome
          - firefox
          - edge

env:
  DOTNET_VERSION: '6.0.x'

jobs:
  run-tests:
    runs-on: windows-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3.6.0

    - name: Setup .NET
      uses: actions/setup-dotnet@v3.4.2
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: Restore Dependencies
      run: dotnet restore

    - name: Build Solution
      run: dotnet build --no-restore

    - name: Run API Tests
      run: >
        dotnet test TAF/EpamAutomationTests.csproj
        --filter "Category=API"
        --logger "trx;LogFileName=api-test-results.trx"
      continue-on-error: true

    - name: Set Browser for UI Tests
      run: |
        $browser = "${{ github.event.inputs.browser || 'chrome' }}"
        (Get-Content TestRunParameters.runsettings) -replace 'value=".*?"', "value=`"$browser`"" | Set-Content TestRunParameters.runsettings

    - name: Run UI Tests
      run: >
        dotnet test TAF/EpamAutomationTests.csproj
        --filter "Category=UI"
        --logger "trx;LogFileName=ui-test-results.trx"
        --settings TestRunParameters.runsettings

    - name: Copy Test Results
      run: |
        mkdir test-results
        Copy-Item -Path TAF/TestResults/*.trx -Destination test-results -Force -ErrorAction SilentlyContinue
        Copy-Item -Path TAF/TestResults/*.png -Destination test-results -Force -ErrorAction SilentlyContinue

    - name: Upload Test Results
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: test-results
        retention-days: 30
