name: Test Pipeline

on:
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 0 * * *'  # Runs daily at midnight
  workflow_dispatch:
    inputs:
      browser:
        description: 'Select browser for UI tests'
        required: true
        default: 'chrome'
        type: choice
        options:
          - chrome
          - firefox
          - edge

env:
  DOTNET_VERSION: '6.0.x'

jobs:
  test:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}
    
    - name: Restore dependencies
      run: dotnet restore
    
    - name: Run API Tests
      run: dotnet test TAF/EpamAutomationTests.csproj --filter "Category=API" --logger "trx;LogFileName=api-test-results.trx" --results-directory TestResults
      continue-on-error: true
    
    - name: Run UI Tests
      run: dotnet test TAF/EpamAutomationTests.csproj --filter "Category=UI" --logger "trx;LogFileName=ui-test-results.trx" --results-directory TestResults
      env:
        BROWSER: ${{ github.event.inputs.browser || 'chrome' }}
    
    - name: Create Test Results Directory
      run: mkdir -p TestResults/Screenshots
    
    - name: Upload Test Results
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: TestResults/
        retention-days: 30
        if-no-files-found: warn
    
    - name: Upload Screenshots
      uses: actions/upload-artifact@v4
      with:
        name: screenshots
        path: TestResults/Screenshots/
        retention-days: 30
        if-no-files-found: warn 