name: Test Automation Pipeline

on:
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 0 * * *'  # Runs daily at midnight
  workflow_dispatch:
    inputs:
      browser:
        description: 'Select browser for UI tests'
        required: true
        default: 'chrome'
        type: choice
        options:
          - chrome
          - firefox
          - edge

env:
  DOTNET_VERSION: '6.0.x'

jobs:
  run-tests:
    runs-on: windows-latest

    env:
      SELECTED_BROWSER: ${{ github.event.inputs.browser || 'chrome' }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3.6.0

      - name: Setup .NET
        uses: actions/setup-dotnet@v3.4.2
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Update RunSettings
        shell: pwsh
        run: |
          $browser = "${{ env.SELECTED_BROWSER }}"
          $runSettingsPath = "TAF/test.runsettings"
          [xml]$runSettings = Get-Content $runSettingsPath
          $runSettings.RunSettings.TestRunParameters.Parameter.value = $browser
          $runSettings.Save($runSettingsPath)

      - name: Restore Dependencies
        run: dotnet restore

      - name: Build Solution
        run: dotnet build --no-restore

      - name: Run Tests
        shell: pwsh
        run: |
          dotnet test TAF/EpamAutomationTests.csproj `
            --settings TAF/test.runsettings `
            --logger "trx;LogFileName=test-results.trx"
          echo "TESTS_EXIT_CODE=$LASTEXITCODE" >> $env:GITHUB_ENV

      - name: Collect Test Results
        if: always()
        run: |
          mkdir -p test-results
          cp TAF/TestResults/*.trx test-results/ 2>$null || echo "No .trx files to copy."
          cp TAF/TestResults/*.png test-results/ 2>$null || echo "No .png files to copy."
          echo "Test Run Summary" > test-results/summary.txt
          echo "Tests Exit Code: $env:TESTS_EXIT_CODE" >> test-results/summary.txt
          echo "Selected Browser: $env:SELECTED_BROWSER" >> test-results/summary.txt

      - name: Upload Test Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: test-results
          retention-days: 30

      - name: Notify Test Results
        if: always()
        run: |
          if ($env:TESTS_EXIT_CODE -ne 0) { Write-Output "Tests Failed" }
          else { Write-Output "All Tests Passed" }
